# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.0.8.121:5000/jxtest-199909/dukecon-feedback
  tag: 1.0.11
  pullPolicy: IfNotPresent
service:
  name: dukecon-feedback
  type: ClusterIP
  externalPort: 80
  internalPort: 8090
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 5
terminationGracePeriodSeconds: 10
javaOpts: ""
dukeconOpts: ""
springProfilesActive: "docker"
